/*
 * WiVRn VR streaming
 * Copyright (C) 2022  Guillaume Meunier <guillaume.meunier@centraliens.net>
 * Copyright (C) 2022  Patrick Nicolas <patricknicolas@laposte.net>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <cmath>
#include <cstdlib>
#include <glm/gtc/packing.hpp>
#include "stream_defoveator.h"

#include <algorithm>
#include "application.h"
#include "utils/ranges.h"
#include "vk/allocation.h"
#include "vk/pipeline.h"
#include "vk/shader.h"
#include "vk/specialization_constants.h"
#include <array>
#include <glm/glm.hpp>
#include <glm/gtx/quaternion.hpp>
#include "scenes/stream_grid.h"
#include "scenes/atlas_tile_grid.h"

#include <cstddef>
#include <vk_mem_alloc.h>
#include <vulkan/vulkan_core.h>
#include <vulkan/vulkan_raii.hpp>
#ifdef __ANDROID__
#include <sys/system_properties.h>
#endif

static int peripheral_smooth_requested()
{
#ifdef __ANDROID__
	char smooth[PROP_VALUE_MAX] = {}, centre[PROP_VALUE_MAX] = {};
	if (__system_property_get("debug.wivrn.nx.peripheral_smooth", smooth) <= 0 ||
	    __system_property_get("debug.wivrn.nx.planar_centre", centre) <= 0 || centre[0] == '0')
		return 0;
#else
	const char * smooth = std::getenv("WIVRN_NX_PERIPHERAL_SMOOTH");
	const char * centre = std::getenv("WIVRN_NX_PLANAR_CENTRE");
	if (!smooth || !centre || centre[0] == '0')
		return 0;
#endif
	return smooth[0] == '3' ? 3 : (smooth[0] == '2' ? 2 : (smooth[0] != '0' ? 1 : 0));
}

static int lowpoly_tiny_requested()
{
#ifdef __ANDROID__
	char value[PROP_VALUE_MAX] = {};
	return __system_property_get("debug.wivrn.nx.kuwahara_fast", value) > 0
	               ? std::clamp(value[0] - '0', 0, 3) : 0;
#else
	const char * value = std::getenv("WIVRN_NX_KUWAHARA_FAST");
	return value ? std::clamp(value[0] - '0', 0, 3) : 0;
#endif
}

struct stream_defoveator::vertex
{
	// output image position
	alignas(8) glm::vec2 position;
	// input texture coordinates
	alignas(8) glm::uvec2 uv;
};

// The grid is generated by stream_grid::emit(), which is a pure function so it can be
// tested without a device (tests/stream_grid_test.cpp proves that an empty mask writes
// exactly the strip this pass drew before it existed). It writes into this buffer
// directly, so the two layouts have to agree.
static_assert(sizeof(wivrn::stream_grid::vertex) == sizeof(stream_defoveator::vertex));
static_assert(alignof(wivrn::stream_grid::vertex) == alignof(stream_defoveator::vertex));
static_assert(offsetof(wivrn::stream_grid::vertex, px) == offsetof(stream_defoveator::vertex, position));
static_assert(offsetof(wivrn::stream_grid::vertex, u) == offsetof(stream_defoveator::vertex, uv));

struct vert_pc
{
	glm::ivec4 rgb_rect;
	glm::ivec4 a_rect;
	std::array<float, 4> scale;
	std::array<float, 4> bias;
	std::array<float, 4> post;
	std::array<float, 4> motion;
	std::array<float, 4> glow;
	std::array<float, 4> deband;
	// [atlas prototype] atlas picture size in samples, and its reciprocal.
};

// 128 bytes: Vulkan's guaranteed minimum maxPushConstantsSize, and exactly what a Pico 4's
// Adreno 650 reports. THIS IS A CEILING, not a current size.
//
// The block was 176 bytes and had been for a while, which looked safe because streams
// worked. They worked because the driver TOLERATED an over-limit block, not because the
// limit was 176: the client now logs `maxPushConstantsSize: 128 bytes` on that device, so
// every one of those builds was over it and getting away with it. Taking it to 208 for the
// edge bleed ended the tolerance, and vkCreateGraphicsPipelines began failing with
// ErrorUnknown.
//
// The failure mode is what makes this worth writing down. The display pipeline is built
// lazily on the first STREAMED frame, so the decoder starts, a few frames arrive, and only
// then does the pass throw, the application thread exit and the client die -- from the
// server, a client that connected, decoded and then vanished. Nothing about it points at a
// shader, and no runtime setting can bisect it, because the block SIZE does not depend on
// the values in it.
//
// What came out to get here:
//   * the atlas prototype's 48 bytes (atlas_size, atlas_geom, atlas_range), which were
//     compile-time constants riding a per-frame block and are now constants in the shader;
//   * the edge bleed's 32, whose five scalars live in lanes the block already had spare --
//     glow.z, glow.w, motion.w and deband.w.
//
// A new parameter goes in a free lane, or into a uniform buffer. It does not get appended.
static_assert(sizeof(vert_pc) == 128);

// And that the atlas prototype's geometry, which used to be 48 bytes of this block and is
// now a set of constants in the shader, still says the same thing. The shader cannot
// include this header, so the pair is pinned here rather than trusted.


// The motion field is stored as one signed byte per axis, scaled by the longest
// vector in the field. R8G8Snorm is one of the formats every implementation must
// support as a linearly filtered sampled image.
static const vk::Format motion_format = vk::Format::eR8G8Snorm;
// [atlas prototype] the per-tile table. Half floats: the warp is a small offset and a
// rotation, neither of which wants 32 bits, and half the table is half the cache.
// [atlas prototype] the synthetic atlas: a RefPicture-shaped pair of planes in the coded
// sample domain. Y at full extent, interleaved Co/Cg at half (4:2:0), which is the v1
// configuration the ADR's measurement table is written against.
static const vk::Format atlas_r16_format = vk::Format::eR16Unorm;
static const vk::Format atlas_rgba8_format = vk::Format::eR8G8B8A8Unorm;

void stream_defoveator::ensure_vertices(size_t num_vertices)
{
	vk::BufferCreateInfo create_info{
	        .size = num_vertices * sizeof(vertex) * view_count,
	        .usage = vk::BufferUsageFlagBits::eVertexBuffer,
	        .sharingMode = vk::SharingMode::eExclusive,
	};

	if (create_info.size <= buffer.info().size)
		return;

	VmaAllocationCreateInfo alloc_info{
	        .requiredFlags = VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT | VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
	};

	buffer = buffer_allocation(device, create_info, alloc_info);
	vertices_size = num_vertices * sizeof(vertex);
}

stream_defoveator::vertex * stream_defoveator::get_vertices(size_t view)
{
	assert(buffer);
	return reinterpret_cast<vertex *>(reinterpret_cast<uintptr_t>(buffer.map()) + view * vertices_size);
}

stream_defoveator::pipeline_t & stream_defoveator::ensure_pipeline(size_t view, vk::Sampler rgb, vk::Sampler a, bool atlas_r8, bool compact_centre)
{
	auto & target = atlas_r8 ? (a ? pipeline_atlas_r8_a[view] : pipeline_atlas_r8_rgb[view])
	                         : (a ? pipeline_a[view] : pipeline_rgb[view]);
	if (*target.pipeline)
		return target;

	std::array samplers{rgb, a};
	int32_t alpha = a ? 1 : 0;

	// Create VkDescriptorSetLayout
	std::array layout_binding{
	        vk::DescriptorSetLayoutBinding{
	                .binding = 0,
	                .descriptorType = vk::DescriptorType::eCombinedImageSampler,
	                .descriptorCount = uint32_t(alpha + 1),
	                .stageFlags = vk::ShaderStageFlagBits::eFragment,
	                .pImmutableSamplers = samplers.data(),
	        },
	        vk::DescriptorSetLayoutBinding{
	                .binding = 1,
	                .descriptorType = vk::DescriptorType::eCombinedImageSampler,
	                .descriptorCount = 1,
	                .stageFlags = vk::ShaderStageFlagBits::eFragment,
	                .pImmutableSamplers = &*motion_sampler,
	        },
	        // Frame smoothing: the previous decoded colour frame. Same immutable sampler
	        // as rgb[0] (it comes from the same decoder, so it needs the same, possibly
	        // YCbCr, conversion). It is always bound, to rgb[0] itself when there is no
	        // previous frame to blend with.
	        vk::DescriptorSetLayoutBinding{
	                .binding = 2,
	                .descriptorType = vk::DescriptorType::eCombinedImageSampler,
	                .descriptorCount = 1,
	                .stageFlags = vk::ShaderStageFlagBits::eFragment,
	                .pImmutableSamplers = samplers.data(),
	        },
	        // [atlas prototype] the atlas planes and the per-tile table. Always in the
	        // layout and always bound, so the two paths share one descriptor set and
	        // the specialization constant is the only difference between them.
	        vk::DescriptorSetLayoutBinding{
	                .binding = 3,
	                .descriptorType = vk::DescriptorType::eCombinedImageSampler,
	                .descriptorCount = 1,
	                .stageFlags = vk::ShaderStageFlagBits::eVertex | vk::ShaderStageFlagBits::eFragment,
	                .pImmutableSamplers = &*atlas_sampler,
	        },
		vk::DescriptorSetLayoutBinding{
		                .binding = 4,
		                .descriptorType = atlas_r8 ? vk::DescriptorType::eCombinedImageSampler : vk::DescriptorType::eStorageImage,
	                .descriptorCount = 1,
	                .stageFlags = vk::ShaderStageFlagBits::eFragment,
	        },
		vk::DescriptorSetLayoutBinding{
		                .binding = 5,
		                .descriptorType = atlas_r8 ? vk::DescriptorType::eStorageBuffer : vk::DescriptorType::eUniformBuffer,
	                .descriptorCount = 1,
	                .stageFlags = vk::ShaderStageFlagBits::eVertex | vk::ShaderStageFlagBits::eFragment,
	        },
	        vk::DescriptorSetLayoutBinding{
	                .binding = 6,
	                .descriptorType = vk::DescriptorType::eCombinedImageSampler,
	                .descriptorCount = 1,
	                .stageFlags = vk::ShaderStageFlagBits::eFragment,
	                .pImmutableSamplers = &*atlas_sampler,
	        },
	};

	target.descriptor_set_layout = device.createDescriptorSetLayout(vk::DescriptorSetLayoutCreateInfo{
	        .bindingCount = layout_binding.size(),
	        .pBindings = layout_binding.data(),
	});

	target.ds = device.allocateDescriptorSets(vk::DescriptorSetAllocateInfo{
	        .descriptorPool = *ds_pool,
	        .descriptorSetCount = 1,
	        .pSetLayouts = &*target.descriptor_set_layout,
	})[0]
	                    .release();

	// pipeline layout
	vk::PushConstantRange pc_range{
	        .stageFlags = vk::ShaderStageFlagBits::eVertex | vk::ShaderStageFlagBits::eFragment,
	        .size = sizeof(vert_pc),
	};

	vk::PipelineLayoutCreateInfo pipeline_layout_info{
	        .setLayoutCount = 1,
	        .pSetLayouts = &*target.descriptor_set_layout,
	        .pushConstantRangeCount = 1,
	        .pPushConstantRanges = &pc_range,
	};

	target.layout = vk::raii::PipelineLayout(device, pipeline_layout_info);

	const auto & vk_device_extensions = application::get_vk_device_extensions();

	// Vertex shader
	auto vertex_shader = load_shader(device, atlas_r8 ? "reprojection_atlas_r8.vert" : "reprojection.vert");

	// Fragment shader
	auto specialization = make_specialization_constants(
	        int32_t(alpha),
	        VkBool32(application::get_hmd_traits().needs_srgb_conversion && !(mutable_alias && atlas_r8 && unorm_baked)),
	        VkBool32(cas_full_baked),
	        VkBool32(fsr_baked),
	        int32_t(atlas_r8 ? 1 : atlas_baked),
	        int32_t(kAtlasTiles),
		int32_t(view),
		VkBool32(lowpoly_baked),
		VkBool32(lowpoly_full_baked),
	        VkBool32(atlas_r8 && atlas_vertex_warp),
	        int32_t(peripheral_smooth_baked),
	        VkBool32(compact_centre),
		int32_t(lowpoly_tiny_baked));
	auto fragment_shader = load_shader(device, atlas_r8 ? "reprojection_atlas_r8.frag" : "reprojection.frag");

	vk::pipeline_builder pipeline_info{
	        .flags = {},
	        .Stages = {
	                {
	                        .stage = vk::ShaderStageFlagBits::eVertex,
	                        .module = *vertex_shader,
	                        .pName = "main",
	                },
	                {
	                        .stage = vk::ShaderStageFlagBits::eFragment,
	                        .module = *fragment_shader,
	                        .pName = "main",
	                        .pSpecializationInfo = specialization,
	                },
	        },
	        .VertexBindingDescriptions = {
	                {
	                        .binding = 0,
	                        .stride = sizeof(vertex),
	                        .inputRate = vk::VertexInputRate::eVertex,
	                },
	        },
	        .VertexAttributeDescriptions = {
	                {
	                        .location = 0,
	                        .binding = 0,
	                        .format = vk::Format::eR32G32Sfloat,
	                        .offset = offsetof(vertex, position),
	                },
	                {
	                        .location = 1,
	                        .binding = 0,
	                        .format = vk::Format::eR32G32Uint,
	                        .offset = offsetof(vertex, uv),
	                },
	        },
	        .InputAssemblyState = {{
	                .topology = vk::PrimitiveTopology::eTriangleStrip,
	        }},
	        .Viewports = {{}},
	        .Scissors = {{}},
	        .RasterizationState = {{
	                .polygonMode = vk::PolygonMode::eFill,
	                .lineWidth = 1,
	        }},
	        .MultisampleState = {{
	                .rasterizationSamples = vk::SampleCountFlagBits::e1,
	        }},
	        .ColorBlendState = {.flags = {}},
	        .ColorBlendAttachments = {{
	                .colorWriteMask = vk::ColorComponentFlagBits::eR | vk::ColorComponentFlagBits::eG | vk::ColorComponentFlagBits::eB | vk::ColorComponentFlagBits::eA,
	        }},
	        .DynamicStates = {vk::DynamicState::eViewport, vk::DynamicState::eScissor},
	        .layout = *target.layout,
	        .renderPass = (atlas_r8 && mutable_alias && unorm_baked) ? *renderpass_unorm : *renderpass,
	        .subpass = 0,
	};

	if (atlas_r8)
	{
		pipeline_info.Stages[0].pSpecializationInfo = specialization;
		const bool vertex_warp = atlas_vertex_warp;
		pipeline_info.VertexAttributeDescriptions.push_back({
		        .location = 2, .binding = 0, .format = vk::Format::eR32Uint,
		        .offset = vertex_warp ? uint32_t(offsetof(wivrn::atlas_tile_grid::vertex, tile)) : 0u});
		if (vertex_warp)
		{
			pipeline_info.VertexBindingDescriptions[0].stride = sizeof(wivrn::atlas_tile_grid::vertex);
			pipeline_info.InputAssemblyState->topology = vk::PrimitiveTopology::eTriangleList;
		}
	}

	target.pipeline = device.createGraphicsPipeline(application::get_pipeline_cache(), pipeline_info);
	return target;
}

stream_defoveator::stream_defoveator(
        vk::raii::Device & device,
        vk::raii::PhysicalDevice & physical_device,
        std::vector<vk::Image> output_images_,
        vk::Extent2D output_extent,
        vk::Format format,
        bool mutable_alias) :
        device(device),
        physical_device(physical_device),
	output_images(std::move(output_images_)),
	output_extent(output_extent),
	mutable_alias(mutable_alias)
{
	// The map is deliberately app-owned: XR_FB_foveation_vulkan is a separate
	// compositor feature and is not needed for a Vulkan render-pass attachment.
	fragment_density_enabled = application::get_fragment_density_map_enabled();
	if (fragment_density_enabled)
	{
		const auto props = physical_device.getFormatProperties(vk::Format::eR8G8Unorm);
		const auto fdm = physical_device.getProperties2<vk::PhysicalDeviceProperties2, vk::PhysicalDeviceFragmentDensityMapPropertiesEXT>();
		const auto & fp = fdm.template get<vk::PhysicalDeviceFragmentDensityMapPropertiesEXT>();
		const bool format_ok = bool(props.optimalTilingFeatures & vk::FormatFeatureFlagBits::eFragmentDensityMapEXT);
		if (!format_ok)
		{
			fragment_density_enabled = false;
			spdlog::warn("FDM requested but RG8 format support is unavailable; using normal defoveation");
		}
		else
		{
			const uint32_t tw = std::max(1u, fp.minFragmentDensityTexelSize.width);
			const uint32_t th = std::max(1u, fp.minFragmentDensityTexelSize.height);
			const uint32_t mw = (output_extent.width + tw - 1) / tw;
			const uint32_t mh = (output_extent.height + th - 1) / th;
			fragment_density_image = image_allocation(device, vk::ImageCreateInfo{
					.imageType = vk::ImageType::e2D, .format = vk::Format::eR8G8Unorm,
					.extent = {mw, mh, 1}, .mipLevels = 1, .arrayLayers = 1,
					.samples = vk::SampleCountFlagBits::e1,
					.usage = vk::ImageUsageFlagBits::eFragmentDensityMapEXT | vk::ImageUsageFlagBits::eTransferDst,
			}, VmaAllocationCreateInfo{.usage = VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE}, "stream FDM");
			fragment_density_view = vk::raii::ImageView(device, vk::ImageViewCreateInfo{
					.image = fragment_density_image, .viewType = vk::ImageViewType::e2D,
					.format = vk::Format::eR8G8Unorm,
					.subresourceRange = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1}});
			std::vector<uint8_t> pixels(size_t(mw) * mh * 2, 255);
			for (uint32_t y = 0; y < mh; ++y)
				for (uint32_t x = 0; x < mw; ++x)
				{
					const float px = (x + .5f) * tw, py = (y + .5f) * th;
					const float dx = std::abs(px - output_extent.width * .5f);
					const float dy = std::abs(py - output_extent.height * .5f);
					const float edge = std::max(dx, dy);
					const int mode = application::get_fragment_density_map_mode();
					const uint8_t d = mode == 2 ? 255 :
					                  edge <= 512.f ? 255 :
					                  mode == 3 ? 64 : (edge <= 768.f ? 128 : 64);
					const size_t i = (size_t(y) * mw + x) * 2;
					pixels[i + 0] = pixels[i + 1] = d;
				}
			buffer_allocation staging(device, vk::BufferCreateInfo{.size = pixels.size(), .usage = vk::BufferUsageFlagBits::eTransferSrc},
					VmaAllocationCreateInfo{.flags = VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT | VMA_ALLOCATION_CREATE_MAPPED_BIT, .usage = VMA_MEMORY_USAGE_AUTO});
			vk::resultCheck(static_cast<vk::Result>(vmaCopyMemoryToAllocation(vk_allocator::instance(), pixels.data(), staging, 0, pixels.size())), "FDM map upload");
			vk::raii::CommandPool pool(device, vk::CommandPoolCreateInfo{.flags = vk::CommandPoolCreateFlagBits::eTransient, .queueFamilyIndex = application::get_vk_queue_family_index()});
			auto cb = std::move(device.allocateCommandBuffers({.commandPool = *pool, .level = vk::CommandBufferLevel::ePrimary, .commandBufferCount = 1})[0]);
			cb.begin({.flags = vk::CommandBufferUsageFlagBits::eOneTimeSubmit});
			cb.pipelineBarrier(vk::PipelineStageFlagBits::eTopOfPipe, vk::PipelineStageFlagBits::eTransfer, {}, {}, {}, vk::ImageMemoryBarrier{.dstAccessMask = vk::AccessFlagBits::eTransferWrite, .oldLayout = vk::ImageLayout::eUndefined, .newLayout = vk::ImageLayout::eTransferDstOptimal, .srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED, .dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED, .image = fragment_density_image, .subresourceRange = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1}});
			cb.copyBufferToImage(staging, fragment_density_image, vk::ImageLayout::eTransferDstOptimal, vk::BufferImageCopy{.imageSubresource = {vk::ImageAspectFlagBits::eColor, 0, 0, 1}, .imageExtent = {mw, mh, 1}});
			cb.pipelineBarrier(vk::PipelineStageFlagBits::eTransfer, vk::PipelineStageFlagBits::eFragmentDensityProcessEXT, {}, {}, {}, vk::ImageMemoryBarrier{.srcAccessMask = vk::AccessFlagBits::eTransferWrite, .dstAccessMask = vk::AccessFlagBits::eFragmentDensityMapReadEXT, .oldLayout = vk::ImageLayout::eTransferDstOptimal, .newLayout = vk::ImageLayout::eFragmentDensityMapOptimalEXT, .srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED, .dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED, .image = fragment_density_image, .subresourceRange = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1}});
			cb.end();
			auto q = application::get_queue().lock();
			q->submit(vk::SubmitInfo{.commandBufferCount = 1, .pCommandBuffers = &*cb});
			q->waitIdle();
			spdlog::info("Static FDM enabled: {}x{} map, texel {}x{}", mw, mh, tw, th);
		}
	}

#ifdef __ANDROID__
	char profile_value[PROP_VALUE_MAX] = {};
	const int profile_len = __system_property_get("debug.wivrn.atlas_vertex_warp", profile_value);
	if (profile_len > 0)
		atlas_vertex_warp = std::atoi(profile_value) == 1;
#else
	if (const char * value = std::getenv("WIVRN_ATLAS_VERTEX_WARP"))
		atlas_vertex_warp = std::atoi(value) == 1;
#endif
	if (atlas_vertex_warp)
		spdlog::info("nxwarp atlas vertex warp enabled");
	// Create renderpass
	vk::AttachmentDescription attachment{
	        .format = format,
	        .samples = vk::SampleCountFlagBits::e1,
	        .loadOp = vk::AttachmentLoadOp::eDontCare,
	        .storeOp = vk::AttachmentStoreOp::eStore,
	        .finalLayout = vk::ImageLayout::eColorAttachmentOptimal,
	};

	vk::AttachmentReference color_ref{
	        .attachment = 0,
	        .layout = vk::ImageLayout::eColorAttachmentOptimal,
	};
	vk::AttachmentDescription density_attachment{
	        .format = vk::Format::eR8G8Unorm, .samples = vk::SampleCountFlagBits::e1,
	        .loadOp = vk::AttachmentLoadOp::eLoad, .storeOp = vk::AttachmentStoreOp::eDontCare,
	        .initialLayout = vk::ImageLayout::eFragmentDensityMapOptimalEXT,
	        .finalLayout = vk::ImageLayout::eFragmentDensityMapOptimalEXT};
	vk::AttachmentReference density_ref{.attachment = 1, .layout = vk::ImageLayout::eFragmentDensityMapOptimalEXT};
	vk::SubpassDescription subpass{
	        .pipelineBindPoint = vk::PipelineBindPoint::eGraphics,
	        .colorAttachmentCount = 1,
	        .pColorAttachments = &color_ref,
	};

	if (fragment_density_enabled)
	{
		std::array attachments{attachment, density_attachment};
		vk::StructureChain renderpass_info{
		        vk::RenderPassCreateInfo{.attachmentCount = 2, .pAttachments = attachments.data(), .subpassCount = 1, .pSubpasses = &subpass},
		        vk::RenderPassFragmentDensityMapCreateInfoEXT{.fragmentDensityMapAttachment = density_ref},
		};
		renderpass = vk::raii::RenderPass(device, renderpass_info.get());
	}
	else
	{
		vk::RenderPassCreateInfo renderpass_info{.attachmentCount = 1, .pAttachments = &attachment, .subpassCount = 1, .pSubpasses = &subpass};
		renderpass = vk::raii::RenderPass(device, renderpass_info);
	}

	std::array pool_sizes{
	        vk::DescriptorPoolSize{
	                .type = vk::DescriptorType::eCombinedImageSampler,
	                // rgb, alpha, the motion field, the previous frame and the two
	                // atlas planes, for both variants
	                .descriptorCount = view_count * 24,
	        },
	        // [atlas prototype] the per-tile table
	        vk::DescriptorPoolSize{
	                .type = vk::DescriptorType::eUniformBuffer,
	                .descriptorCount = view_count * 2,
	        },
		vk::DescriptorPoolSize{
		                .type = vk::DescriptorType::eStorageImage,
		                .descriptorCount = view_count * 2,
		},
		vk::DescriptorPoolSize{
		                .type = vk::DescriptorType::eStorageBuffer,
		                .descriptorCount = view_count * 2,
		},
	};

	ds_pool = device.createDescriptorPool(vk::DescriptorPoolCreateInfo{
	        .maxSets = view_count * 4,
	        .poolSizeCount = pool_sizes.size(),
	        .pPoolSizes = pool_sizes.data(),
	});

	// [atlas prototype] bilinear, by the sampler, as ADR-0029 section 5 asks for.
	atlas_sampler = device.createSampler(vk::SamplerCreateInfo{
	        .magFilter = vk::Filter::eLinear,
	        .minFilter = vk::Filter::eLinear,
	        .mipmapMode = vk::SamplerMipmapMode::eNearest,
	        .addressModeU = vk::SamplerAddressMode::eClampToEdge,
	        .addressModeV = vk::SamplerAddressMode::eClampToEdge,
	        .addressModeW = vk::SamplerAddressMode::eClampToEdge,
	});

	motion_sampler = device.createSampler(vk::SamplerCreateInfo{
	        .magFilter = vk::Filter::eLinear,
	        .minFilter = vk::Filter::eLinear,
	        .mipmapMode = vk::SamplerMipmapMode::eNearest,
	        .addressModeU = vk::SamplerAddressMode::eClampToEdge,
	        .addressModeV = vk::SamplerAddressMode::eClampToEdge,
	        .addressModeW = vk::SamplerAddressMode::eClampToEdge,
	});

	// Create image views and framebuffers
	output_image_views.reserve(output_images.size() * view_count);
	framebuffers.reserve(output_images.size() * view_count);
	for (vk::Image image: output_images)
	{
		for (uint32_t view = 0; view < view_count; ++view)
		{
			vk::ImageViewCreateInfo iv_info{
			        .image = image,
			        .viewType = vk::ImageViewType::e2DArray,
			        .format = format,
			        .components = {
			                .r = vk::ComponentSwizzle::eIdentity,
			                .g = vk::ComponentSwizzle::eIdentity,
			                .b = vk::ComponentSwizzle::eIdentity,
			                .a = vk::ComponentSwizzle::eIdentity,
			        },
			        .subresourceRange = {
			                .aspectMask = vk::ImageAspectFlagBits::eColor,
			                .baseMipLevel = 0,
			                .levelCount = 1,
			                .baseArrayLayer = view,
			                .layerCount = 1,
			        },
			};

			output_image_views.emplace_back(device, iv_info);

			vk::FramebufferCreateInfo fb_create_info{
			        .renderPass = *renderpass,
			        .width = output_extent.width,
			        .height = output_extent.height,
			        .layers = 1,
			};
			std::array views{*output_image_views.back(), *fragment_density_view};
			if (fragment_density_enabled)
				fb_create_info.setAttachments(views);
			else
				fb_create_info.setAttachments(*output_image_views.back());

			framebuffers.emplace_back(device, fb_create_info);
		}
	}
	if (mutable_alias)
	{
		try
		{
		const vk::Format view_format = format == vk::Format::eR8G8B8A8Srgb ? vk::Format::eR8G8B8A8Unorm : vk::Format::eB8G8R8A8Unorm;
		vk::AttachmentDescription unorm_attachment{
		        .format = view_format, .samples = vk::SampleCountFlagBits::e1,
		        .loadOp = vk::AttachmentLoadOp::eDontCare, .storeOp = vk::AttachmentStoreOp::eStore,
		        .finalLayout = vk::ImageLayout::eColorAttachmentOptimal,
		};
		vk::AttachmentReference unorm_ref{.attachment = 0, .layout = vk::ImageLayout::eColorAttachmentOptimal};
		vk::SubpassDescription unorm_subpass{.pipelineBindPoint = vk::PipelineBindPoint::eGraphics,
		        .colorAttachmentCount = 1, .pColorAttachments = &unorm_ref};
		if (fragment_density_enabled)
		{
			std::array attachments{unorm_attachment, density_attachment};
			vk::StructureChain unorm_info{
			        vk::RenderPassCreateInfo{.attachmentCount = 2, .pAttachments = attachments.data(), .subpassCount = 1, .pSubpasses = &unorm_subpass},
			        vk::RenderPassFragmentDensityMapCreateInfoEXT{.fragmentDensityMapAttachment = density_ref},
			};
			renderpass_unorm = vk::raii::RenderPass(device, unorm_info.get());
		}
		else
		{
			vk::RenderPassCreateInfo unorm_info{.attachmentCount = 1, .pAttachments = &unorm_attachment, .subpassCount = 1, .pSubpasses = &unorm_subpass};
			renderpass_unorm = vk::raii::RenderPass(device, unorm_info);
		}
		for (vk::Image image: output_images)
			for (uint32_t view = 0; view < view_count; ++view)
			{
				output_image_views_unorm.emplace_back(device, vk::ImageViewCreateInfo{
				        .image = image, .viewType = vk::ImageViewType::e2DArray, .format = view_format,
				        .subresourceRange = {.aspectMask = vk::ImageAspectFlagBits::eColor,
				                .levelCount = 1, .baseArrayLayer = view, .layerCount = 1}});
				vk::FramebufferCreateInfo fb{.renderPass = *renderpass_unorm, .width = output_extent.width,
				        .height = output_extent.height, .layers = 1};
				std::array views{*output_image_views_unorm.back(), *fragment_density_view};
				if (fragment_density_enabled)
					fb.setAttachments(views);
				else
					fb.setAttachments(*output_image_views_unorm.back());
				framebuffers_unorm.emplace_back(device, fb);
			}
		spdlog::info("Atlas UNORM attachment views ready");
		}
		catch (const vk::SystemError & e)
		{
			spdlog::warn("UNORM XR view unavailable ({}); using SRGB render view", e.what());
			framebuffers_unorm.clear();
			output_image_views_unorm.clear();
			renderpass_unorm = nullptr;
			this->mutable_alias = false;
		}
	}
}

void stream_defoveator::reset_pipelines()
{
	for (auto & p: pipeline_rgb)
		p = {};
	for (auto & p: pipeline_a)
		p = {};
	for (auto & p: pipeline_atlas_r8_rgb)
		p = {};
	for (auto & p: pipeline_atlas_r8_a)
		p = {};
	// Reclaim the descriptor sets; the pool is sized for one generation and has
	// no free-flag, so without this a rebuild (resolution/codec change, or the
	// CAS full-kernel toggle) exhausts it and allocateDescriptorSets throws.
	ds_pool.reset();
}

// Makes sure the motion texture exists at the requested size and is readable by the
// fragment shader. The texture is bound by every pass, whether motion smoothing is
// in use or not, so it must be valid even when there is no field: a 1x1 texture of
// zeroes then, which the shader never reads because the step is zero.
void stream_defoveator::ensure_motion_image(vk::raii::CommandBuffer & command_buffer, uint32_t width, uint32_t height)
{
	if (motion_image and motion_width == width and motion_height == height)
		return;

	// Nothing can still be reading it: the caller waits on the frame fence before
	// recording anything.
	motion_views.clear();
	motion_image = image_allocation(
	        device,
	        vk::ImageCreateInfo{
	                .imageType = vk::ImageType::e2D,
	                .format = motion_format,
	                .extent = {.width = width, .height = height, .depth = 1},
	                .mipLevels = 1,
	                .arrayLayers = view_count,
	                .samples = vk::SampleCountFlagBits::e1,
	                .usage = vk::ImageUsageFlagBits::eSampled | vk::ImageUsageFlagBits::eTransferDst,
	        },
	        VmaAllocationCreateInfo{.usage = VMA_MEMORY_USAGE_AUTO});

	motion_views.reserve(view_count);
	for (uint32_t view = 0; view < view_count; ++view)
	{
		motion_views.emplace_back(
		        device,
		        vk::ImageViewCreateInfo{
		                .image = motion_image,
		                .viewType = vk::ImageViewType::e2D,
		                .format = motion_format,
		                .subresourceRange = {
		                        .aspectMask = vk::ImageAspectFlagBits::eColor,
		                        .levelCount = 1,
		                        .baseArrayLayer = view,
		                        .layerCount = 1,
		                },
		        });
	}

	motion_staging = buffer_allocation(
	        device,
	        vk::BufferCreateInfo{
	                .size = vk::DeviceSize(width) * height * view_count * 2,
	                .usage = vk::BufferUsageFlagBits::eTransferSrc,
	        },
	        VmaAllocationCreateInfo{
	                .flags = VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT,
	                .usage = VMA_MEMORY_USAGE_AUTO_PREFER_HOST,
	        });

	motion_width = width;
	motion_height = height;
	motion_frame = uint64_t(-1);
	motion_ready = false;
}

// Total source pixels one foveation run covers, which is the picture's size in the decoded
// image: the grid's uv accumulator walks exactly this far.
static uint32_t source_extent(const std::vector<uint16_t> & param)
{
	uint32_t res = 0;
	for (auto n: param)
		res += n;
	return res;
}

// This eye's picture inside the decoded colour image, HORIZONTALLY, in normalized
// coordinates and inset by half a texel: {x_lo, x_hi}.
//
// `rect.offset` is where this eye's picture starts and `rect.extent` is the WHOLE image,
// because the shader normalizes with (uv + rgb_rect.xy) / rgb_rect.zw. At one eye per
// stream the offset is zero and this is very nearly {0, 1}; with the NX Warp encoder
// pairing the eyes it is one half of the image or the other, and that is the case the
// edge bleed's stretch must not cross.
//
// Horizontally only, because the pair is laid out side by side and a picture always spans
// the image vertically -- the shader takes the vertical limits from the plain half-texel
// inset it already computes. That also keeps this to two floats, which is what there was
// room for without growing the push constant block; see the static_assert on vert_pc.
static std::array<float, 2> eye_x_limits(const vk::Rect2D & rect,
                                         const wivrn::to_headset::foveation_parameter & p)
{
	const float w = float(std::max(1u, rect.extent.width));
	const float x0 = float(rect.offset.x);
	const float pw = float(source_extent(p.x));
	return {(x0 + 0.5f) / w, (x0 + pw - 0.5f) / w};
}

static size_t required_vertices(const wivrn::to_headset::foveation_parameter & p)
{
	// strips are constructed like this:
	// 0 2 4
	// 1 3 5 5*
	// there is one such line per value in y
	// the last element is repeated to break the line
	return wivrn::stream_grid::max_vertices(p.x.size(), p.y.size());
}


// [atlas prototype] Build (once) and refill (every frame) the synthetic atlas and table.
//
// ADR-0029 section 5 is the specification being priced: the client warps each atlas tile
// from its source pose to the pose it wants IN ONE STEP, sampling an atlas laid out as a
// RefPicture (whole eye picture, Y/Co/Cg in the coded sample domain) through a per-tile
// 64-byte table whose first 36 bytes are the composed homography C. The late-latch
// composition C . H(pose_t <- pose_N) is per TILE and is done here, in float, on the
// host: 578 3x3 multiplies a frame, which is why it is not in the fragment shader and
// why it is not what the budget is about.
//
// The pixels are synthetic and meaningless. What is being measured is the per-fragment
// cost of the shape: three uniform reads, one homography with its perspective divide,
// two bilinear taps and the inverse colour transform. The table is refilled every frame
// -- a real one changes every frame, and a table a driver could hoist out of the loop
// would measure nothing.
void stream_defoveator::ensure_atlas_table(vk::raii::CommandBuffer & command_buffer)
{
	if (not atlas_baked)
		return;

	const uint32_t P = kAtlasPicture, H = kAtlasPicture / 2;
	const size_t entries = size_t(kAtlasTiles) * kAtlasTiles * view_count;

	if (not atlas_r16_image)
	{
		// Can this device sample AND store the same R16_UNORM memory? Mode 2 is not
		// slow without it, it is unmeasurable, so it is reported rather than skipped.
		const auto fp = physical_device.getFormatProperties(atlas_r16_format);
		atlas_storage_ok = bool(fp.optimalTilingFeatures & vk::FormatFeatureFlagBits::eStorageImage);
		const bool sampled_ok = bool(fp.optimalTilingFeatures & vk::FormatFeatureFlagBits::eSampledImageFilterLinear);
		spdlog::info("nxwarp atlas prototype: R16_UNORM linear-filtered sampling {}, storage image {}",
		             sampled_ok ? "yes" : "NO", atlas_storage_ok ? "yes" : "NO");

		atlas_r16_image = image_allocation(
		        device,
		        vk::ImageCreateInfo{
		                .imageType = vk::ImageType::e2D,
		                .format = atlas_r16_format,
		                .extent = {.width = kAtlasW, .height = kAtlasH, .depth = 1},
		                .mipLevels = 1,
		                .arrayLayers = 1,
		                .samples = vk::SampleCountFlagBits::e1,
		                .usage = vk::ImageUsageFlagBits::eSampled | vk::ImageUsageFlagBits::eTransferDst |
		                         (atlas_storage_ok ? vk::ImageUsageFlagBits::eStorage : vk::ImageUsageFlagBits{}),
		        },
		        VmaAllocationCreateInfo{.usage = VMA_MEMORY_USAGE_AUTO});

		// Two views of ONE allocation, which is the arrangement being priced: the
		// decoder keeps its u16 ring and merely exposes a sampled view of it.
		vk::ImageViewCreateInfo iv{
		        .image = atlas_r16_image,
		        .viewType = vk::ImageViewType::e2D,
		        .format = atlas_r16_format,
		        .subresourceRange = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1},
		};
		atlas_r16_sampled = vk::raii::ImageView(device, iv);
		atlas_r16_storage = vk::raii::ImageView(device, iv);

		// The converted copy, for the lower bound.
		atlas_rgba8_image = image_allocation(
		        device,
		        vk::ImageCreateInfo{
		                .imageType = vk::ImageType::e2D,
		                .format = atlas_rgba8_format,
		                .extent = {.width = kAtlasW, .height = kAtlasPicture, .depth = 1},
		                .mipLevels = 1,
		                .arrayLayers = 1,
		                .samples = vk::SampleCountFlagBits::e1,
		                .usage = vk::ImageUsageFlagBits::eSampled | vk::ImageUsageFlagBits::eTransferDst,
		        },
		        VmaAllocationCreateInfo{.usage = VMA_MEMORY_USAGE_AUTO});
		atlas_rgba8_view = vk::raii::ImageView(
		        device,
		        vk::ImageViewCreateInfo{
		                .image = atlas_rgba8_image,
		                .viewType = vk::ImageViewType::e2D,
		                .format = atlas_rgba8_format,
		                .subresourceRange = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1},
		        });

		atlas_table_buffer = buffer_allocation(
		        device,
		        vk::BufferCreateInfo{
		                .size = vk::DeviceSize(entries) * 64,
		                .usage = vk::BufferUsageFlagBits::eUniformBuffer,
		        },
		        VmaAllocationCreateInfo{
		                .flags = VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT | VMA_ALLOCATION_CREATE_MAPPED_BIT,
		                .usage = VMA_MEMORY_USAGE_AUTO,
		        });
		atlas_ready = false;
	}

	// The atlas pixels are filled once: their CONTENT does not affect what is being
	// measured, only the layout, the extent and the element width do. Re-uploading
	// 7 MB a frame would measure the upload instead of the pass.
	if (not atlas_ready)
	{
		const vk::DeviceSize r16_bytes = vk::DeviceSize(kAtlasW) * kAtlasH * 2;
		const vk::DeviceSize rgba_bytes = vk::DeviceSize(kAtlasW) * kAtlasPicture * 4;
		buffer_allocation staging(
		        device,
		        vk::BufferCreateInfo{
		                .size = r16_bytes + rgba_bytes,
		                .usage = vk::BufferUsageFlagBits::eTransferSrc,
		        },
		        VmaAllocationCreateInfo{
		                .flags = VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT,
		                .usage = VMA_MEMORY_USAGE_AUTO,
		        });
		{
			std::vector<uint8_t> px(size_t(r16_bytes + rgba_bytes));
			for (size_t i = 0; i < px.size(); ++i)
				px[i] = uint8_t((i * 37 + (i >> 7) * 11) & 0xff);
			vmaCopyMemoryToAllocation(vk_allocator::instance(), px.data(), staging, 0, px.size());
		}

		auto barrier = [&](vk::Image img, vk::ImageLayout from, vk::ImageLayout to,
		                   vk::AccessFlags src, vk::AccessFlags dst,
		                   vk::PipelineStageFlags s0, vk::PipelineStageFlags s1) {
			vk::ImageMemoryBarrier b{
			        .srcAccessMask = src,
			        .dstAccessMask = dst,
			        .oldLayout = from,
			        .newLayout = to,
			        .image = img,
			        .subresourceRange = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1},
			};
			command_buffer.pipelineBarrier(s0, s1, {}, {}, {}, b);
		};

		barrier(atlas_r16_image, vk::ImageLayout::eUndefined, vk::ImageLayout::eTransferDstOptimal,
		        {}, vk::AccessFlagBits::eTransferWrite,
		        vk::PipelineStageFlagBits::eTopOfPipe, vk::PipelineStageFlagBits::eTransfer);
		command_buffer.copyBufferToImage(
		        staging, atlas_r16_image, vk::ImageLayout::eTransferDstOptimal,
		        vk::BufferImageCopy{
		                .imageSubresource = {vk::ImageAspectFlagBits::eColor, 0, 0, 1},
		                .imageExtent = {kAtlasW, kAtlasH, 1},
		        });
		// GENERAL, not ShaderReadOnly: one allocation read through a sampled view AND
		// a storage view has to be in a layout both can use, which is what a decoder
		// exposing its own ring would have to do too.
		barrier(atlas_r16_image, vk::ImageLayout::eTransferDstOptimal, vk::ImageLayout::eGeneral,
		        vk::AccessFlagBits::eTransferWrite, vk::AccessFlagBits::eShaderRead,
		        vk::PipelineStageFlagBits::eTransfer, vk::PipelineStageFlagBits::eFragmentShader);

		barrier(atlas_rgba8_image, vk::ImageLayout::eUndefined, vk::ImageLayout::eTransferDstOptimal,
		        {}, vk::AccessFlagBits::eTransferWrite,
		        vk::PipelineStageFlagBits::eTopOfPipe, vk::PipelineStageFlagBits::eTransfer);
		command_buffer.copyBufferToImage(
		        staging, atlas_rgba8_image, vk::ImageLayout::eTransferDstOptimal,
		        vk::BufferImageCopy{
		                .bufferOffset = r16_bytes,
		                .imageSubresource = {vk::ImageAspectFlagBits::eColor, 0, 0, 1},
		                .imageExtent = {kAtlasW, kAtlasPicture, 1},
		        });
		barrier(atlas_rgba8_image, vk::ImageLayout::eTransferDstOptimal, vk::ImageLayout::eShaderReadOnlyOptimal,
		        vk::AccessFlagBits::eTransferWrite, vk::AccessFlagBits::eShaderRead,
		        vk::PipelineStageFlagBits::eTransfer, vk::PipelineStageFlagBits::eFragmentShader);

		atlas_staging_keepalive = std::move(staging);
		atlas_ready = true;
	}

	// The table, every frame. Per tile: C composed with the late-latch pose delta, in
	// float, exactly as ADR-0029 section 5 has the client do it.
	{
		++atlas_seed;
		const float ang = float(atlas_seed) * 0.0007f;
		// H(pose_t <- pose_N): one small rotation about the picture centre, which is
		// what a refresh of head motion comes to.
		const float ch = std::cos(ang), sh = std::sin(ang);
		float * dst = static_cast<float *>(atlas_table_buffer.map());
		size_t k = 0;
		for (uint32_t view = 0; view < view_count; ++view)
			for (uint32_t ty = 0; ty < kAtlasTiles; ++ty)
				for (uint32_t tx = 0; tx < kAtlasTiles; ++tx)
				{
					// The tile's own C, as the codec would have composed it over
					// however many frames since it was last coded: a small
					// rotation, a small scale and a perspective term.
					const uint32_t n = (tx * 73856093u) ^ (ty * 19349663u) ^ (view * 83492791u);
					const float r0 = float((n >> 8) & 0xffff) / 65535.f - 0.5f;
					const float r1 = float((n >> 16) & 0xffff) / 65535.f - 0.5f;
					const float a = r0 * 0.01f + ang;
					const float c = std::cos(a), s = std::sin(a);
					const float sc = 1.f + r1 * 0.01f;
					// C . H(pose_t <- pose_N), both rotations, composed in float.
					const float cc = c * ch - s * sh, ss = s * ch + c * sh;
					const float C[9] = {
					        sc * cc, -sc * ss, r0 * 8.f,
					        sc * ss, sc * cc, r1 * 8.f,
					        r0 * 2e-6f, r1 * 2e-6f, 1.f,
					};
					dst[k + 0] = C[0]; dst[k + 1] = C[1]; dst[k + 2] = C[2]; dst[k + 3] = 0;
					dst[k + 4] = C[3]; dst[k + 5] = C[4]; dst[k + 6] = C[5]; dst[k + 7] = 0;
					dst[k + 8] = C[6]; dst[k + 9] = C[7]; dst[k + 10] = C[8]; dst[k + 11] = 0;
					// src_frame, gen, flags, res_level
					dst[k + 12] = float(atlas_seed);
					dst[k + 13] = 1.f;
					dst[k + 14] = 1.f;
					dst[k + 15] = 0.f;
					k += 16;
				}
		atlas_table_buffer.unmap();
	}
}

void stream_defoveator::defoveate(vk::raii::CommandBuffer & command_buffer,
                                  const std::array<wivrn::to_headset::foveation_parameter, 2> & foveation,
                                  const std::array<input, 2> & inputs,
                                  std::array<float, 4> scale,
                                  std::array<float, 4> bias,
                                  const post_processing & post,
                                  const motion_warp & motion,
                                  const frame_blend & blend,
                                  int destination,
                                  bool cas_full_kernel,
                                  bool fsr,
                                  int atlas_prototype)
{
	if (destination < 0 || destination >= (int)output_images.size())
		throw std::runtime_error("Invalid destination image index");

	// The CAS kernel, the FSR path and the low poly filter are specialization constants,
	// so a change to any of them means rebuilding the pipelines. The caller has waited on the frame fence before recording,
	// so nothing is still reading the old pipelines. They only ever flip from a settings
	// toggle, a rare event.
	const bool lowpoly = post.low_poly > 0;
	const int lowpoly_tiny = lowpoly && !post.low_poly_full ? lowpoly_tiny_requested() : 0;
	const bool neutral_color = std::all_of(scale.begin(), scale.end(), [](float v) { return v == 1.f; }) &&
	                            std::all_of(bias.begin(), bias.end(), [](float v) { return v == 0.f; });
	const bool want_unorm = mutable_alias && neutral_color;
	const int want_peripheral_smooth = atlas_prototype == 0 ? peripheral_smooth_requested() : 0;
	const bool want_compact_centre = inputs[0].compact_centre || inputs[1].compact_centre;
	if (want_compact_centre != compact_centre_baked or want_unorm != unorm_baked or cas_full_kernel != cas_full_baked or fsr != fsr_baked or atlas_prototype != atlas_baked or
	    lowpoly != lowpoly_baked or post.low_poly_full != lowpoly_full_baked || lowpoly_tiny != lowpoly_tiny_baked ||
	    want_peripheral_smooth != peripheral_smooth_baked)
	{
		reset_pipelines();
		cas_full_baked = cas_full_kernel;
		fsr_baked = fsr;
		atlas_baked = atlas_prototype;
		compact_centre_baked = want_compact_centre;
		lowpoly_baked = lowpoly;
		lowpoly_full_baked = post.low_poly_full;
		lowpoly_tiny_baked = lowpoly_tiny;
		peripheral_smooth_baked = want_peripheral_smooth;
		spdlog::info("NX peripheral smoothing mode {}", peripheral_smooth_baked);
		unorm_baked = want_unorm;
		if (mutable_alias)
			spdlog::info("Atlas UNORM attachment path {}", unorm_baked ? "active" : "paused for color fade");
	}

	// [atlas prototype] the table has to exist before a descriptor can point at it, so
	// it is built the first time the prototype is asked for and refilled every frame
	// after -- a real atlas table changes every frame, and a table the driver could
	// hoist out of the loop would measure the wrong thing.
	ensure_atlas_table(command_buffer);

	ensure_vertices(std::max(required_vertices(foveation[0]), required_vertices(foveation[1])));

	// Motion field: keep whatever is already in the texture unless a new one came in
	const wivrn::motion_field_data * field = motion.field;
	if (field and (field->width == 0 or field->height == 0 or
	               field->vectors.size() != size_t(field->width) * field->height * view_count * 2))
		field = nullptr;

	float motion_step = field ? motion.step : 0.f;
	float motion_scale = field ? field->scale : 0.f;

	// Without a field the texture is left as it is rather than dropped: the shader
	// does not read it when the step is zero, and a field usually comes back within
	// a frame or two. Reallocating on every gap would be pointless churn.
	ensure_motion_image(
	        command_buffer,
	        field ? field->width : std::max(motion_width, 1u),
	        field ? field->height : std::max(motion_height, 1u));

	if (not motion_ready or (field and field->frame_idx != motion_frame))
	{
		const size_t size = size_t(motion_width) * motion_height * view_count * 2;
		if (field and size_t(field->width) * field->height * view_count * 2 == size)
			vmaCopyMemoryToAllocation(vk_allocator::instance(), field->vectors.data(), motion_staging, 0, size);
		else
		{
			std::vector<int8_t> zeroes(size, 0);
			vmaCopyMemoryToAllocation(vk_allocator::instance(), zeroes.data(), motion_staging, 0, size);
		}

		vk::ImageMemoryBarrier to_transfer{
		        .srcAccessMask = vk::AccessFlagBits::eNone,
		        .dstAccessMask = vk::AccessFlagBits::eTransferWrite,
		        .oldLayout = vk::ImageLayout::eUndefined,
		        .newLayout = vk::ImageLayout::eTransferDstOptimal,
		        .image = motion_image,
		        .subresourceRange = {
		                .aspectMask = vk::ImageAspectFlagBits::eColor,
		                .levelCount = 1,
		                .layerCount = view_count,
		        },
		};
		command_buffer.pipelineBarrier(
		        vk::PipelineStageFlagBits::eTopOfPipe,
		        vk::PipelineStageFlagBits::eTransfer,
		        {},
		        {},
		        {},
		        to_transfer);

		// The two layers are consecutive in the packet, which is exactly how a
		// multi layer copy expects them
		command_buffer.copyBufferToImage(
		        motion_staging,
		        motion_image,
		        vk::ImageLayout::eTransferDstOptimal,
		        vk::BufferImageCopy{
		                .imageSubresource = {
		                        .aspectMask = vk::ImageAspectFlagBits::eColor,
		                        .layerCount = view_count,
		                },
		                .imageExtent = {.width = motion_width, .height = motion_height, .depth = 1},
		        });

		vk::ImageMemoryBarrier to_read{
		        .srcAccessMask = vk::AccessFlagBits::eTransferWrite,
		        .dstAccessMask = vk::AccessFlagBits::eShaderRead,
		        .oldLayout = vk::ImageLayout::eTransferDstOptimal,
		        .newLayout = vk::ImageLayout::eShaderReadOnlyOptimal,
		        .image = motion_image,
		        .subresourceRange = {
		                .aspectMask = vk::ImageAspectFlagBits::eColor,
		                .levelCount = 1,
		                .layerCount = view_count,
		        },
		};
		command_buffer.pipelineBarrier(
		        vk::PipelineStageFlagBits::eTransfer,
		        vk::PipelineStageFlagBits::eFragmentShader,
		        {},
		        {},
		        {},
		        to_read);

		motion_ready = true;
		motion_frame = field ? field->frame_idx : uint64_t(-1);
	}

	for (size_t view = 0; view < view_count; ++view)
	{
		const auto out_size = defoveated_size(foveation[view], out_scale);
		auto vertices = get_vertices(view);
		const auto & [px, py] = foveation[view];
		assert(px.size() % 2 == 1);
		assert(py.size() % 2 == 1);

		command_buffer.setScissor(
		        0,
		        vk::Rect2D{
		                .extent = {.width = uint32_t(out_size.width), .height = uint32_t(out_size.height)},
		        });
		command_buffer.setViewport(
		        0,
		        vk::Viewport{
		                .x = 0,
		                .y = 0,
		                .width = float(out_size.width),
		                .height = float(out_size.height),
		                .minDepth = 0,
		                .maxDepth = 1,
		        });

		// The strip, minus any cells the optics can never show. An empty mask -- which
		// is what every failure path in stream_grid produces, and what the caller
		// passes when the setting is off -- writes the grid exactly as it always was.
		const auto & mask = view < lens_masks.size() ? lens_masks[view] : wivrn::stream_grid::cell_mask{};
		drawn_vertices[view] = wivrn::stream_grid::emit_full_view(
		        px,
		        py,
		        mask,
		        reinterpret_cast<wivrn::stream_grid::vertex *>(vertices),
		        vertices_size / sizeof(vertex));
	}

	for (size_t view = 0; view < view_count; ++view)
	{
		const auto & input = inputs[view];
		const bool atlas_r8 = input.atlas_valid && input.atlas_table != nullptr && input.atlas_table_bytes != 0;
		const bool use_unorm = unorm_baked && atlas_r8;
		vk::RenderPassBeginInfo begin_info{
		        .renderPass = use_unorm ? *renderpass_unorm : *renderpass,
		        .framebuffer = use_unorm ? *framebuffers_unorm[destination * view_count + view] : *framebuffers[destination * view_count + view],
		        .renderArea = {
		                .offset = {0, 0},
		                .extent = output_extent,
		        },
		};

		auto & pipeline = ensure_pipeline(view, input.sampler_rgb, input.sampler_a, atlas_r8, input.compact_centre);
		if (atlas_r8 && atlas_vertex_warp &&
		    (!atlas_mesh_buffers[view] || atlas_mesh_extents[view] != input.atlas_extents[0] ||
		     atlas_mesh_foveation[view].x != foveation[view].x ||
		     atlas_mesh_foveation[view].y != foveation[view].y))
		{
			const auto & f = foveation[view];
			// The decoded allocation can include the final tile's padding (e.g.
			// 2176 pixels for a 2160-pixel view). The visible grid may omit that
			// padding, but its row stride must still address the same tile table.
			const auto source_width = wivrn::atlas_tile_grid::extent(f.x);
			const auto source_height = wivrn::atlas_tile_grid::extent(f.y);
			const auto picture = input.atlas_extents[0];
			if (source_width > picture.width / 2 || source_height > picture.height ||
			    (source_width + 63) / 64 != (picture.width / 2 + 63) / 64)
				throw std::runtime_error("Native atlas vertex grid does not match decoded source extent");
			const size_t count = wivrn::atlas_tile_grid::required_vertices(f.x, f.y);
			if (!count)
				throw std::runtime_error("Empty native atlas vertex grid");
			const vk::BufferCreateInfo info{
			        .size = count * sizeof(wivrn::atlas_tile_grid::vertex),
			        .usage = vk::BufferUsageFlagBits::eVertexBuffer,
			        .sharingMode = vk::SharingMode::eExclusive};
			const VmaAllocationCreateInfo alloc{
			        .requiredFlags = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT};
			atlas_mesh_buffers[view] = buffer_allocation(device, info, alloc);
			atlas_mesh_counts[view] = wivrn::atlas_tile_grid::emit(f.x, f.y,
			        static_cast<wivrn::atlas_tile_grid::vertex *>(atlas_mesh_buffers[view].map()), count);
			atlas_mesh_buffers[view].unmap();
			atlas_mesh_foveation[view] = f;
			atlas_mesh_extents[view] = input.atlas_extents[0];
			spdlog::info("nxwarp atlas vertex grid eye {}: {}x{} source, {} vertices", view,
			        wivrn::atlas_tile_grid::extent(f.x), wivrn::atlas_tile_grid::extent(f.y), atlas_mesh_counts[view]);
		}


		std::array image_info{
		        vk::DescriptorImageInfo{
		                .sampler = input.sampler_rgb,
		                .imageView = input.rgb,
		                .imageLayout = input.layout_rgb,
		        },
		        vk::DescriptorImageInfo{
		                .sampler = input.sampler_a,
		                .imageView = input.a,
		                .imageLayout = input.layout_a,
		        },
		};

		vk::DescriptorImageInfo motion_info{
		        .sampler = *motion_sampler,
		        .imageView = *motion_views[view],
		        .imageLayout = vk::ImageLayout::eShaderReadOnlyOptimal,
		};

		// Frame smoothing. Without a previous frame the binding still has to be a valid
		// image, so it points at this frame's own colour image and the weight is forced
		// to zero: the shader then never reads it and the result is unchanged.
		const bool blend_on = blend.weight > 0 and input.prev_rgb;
		vk::DescriptorImageInfo prev_info{
		        .sampler = input.sampler_rgb,
		        .imageView = blend_on ? input.prev_rgb : input.rgb,
		        .imageLayout = blend_on ? input.layout_prev_rgb : input.layout_rgb,
		};

		// [atlas prototype] always bound so the two paths share a descriptor set.
		// With no table built yet (the prototype is off) it points at the motion
		// texture, which the shader never reads on that path.
		// [atlas prototype] Always bound so both paths share one descriptor set; with
		// nothing allocated (the prototype is off) they point at images the shader
		// never reads on that path.
		vk::DescriptorImageInfo atlas_r16_info{
		        .sampler = *atlas_sampler,
		        .imageView = atlas_r8 ? input.atlas_views[0] : (*atlas_r16_sampled ? *atlas_r16_sampled : *motion_views[view]),
		        .imageLayout = atlas_r8 ? vk::ImageLayout::eShaderReadOnlyOptimal : (*atlas_r16_sampled ? vk::ImageLayout::eGeneral : vk::ImageLayout::eShaderReadOnlyOptimal),
		};
		vk::DescriptorImageInfo atlas_store_info{
		        .sampler = *atlas_sampler,
		        .imageView = atlas_r8 ? input.atlas_views[1] : ((atlas_storage_ok and *atlas_r16_storage) ? *atlas_r16_storage : *output_image_views[destination * view_count + view]),
		        .imageLayout = atlas_r8 ? vk::ImageLayout::eShaderReadOnlyOptimal : vk::ImageLayout::eGeneral,
		};
		vk::DescriptorImageInfo atlas_rgba8_info{
		        .imageView = *atlas_rgba8_view ? *atlas_rgba8_view : *motion_views[view],
		        .imageLayout = vk::ImageLayout::eShaderReadOnlyOptimal,
		};
		vk::DescriptorBufferInfo atlas_table_info{
		        .buffer = atlas_r8 ? input.atlas_table : (atlas_table_buffer ? vk::Buffer(atlas_table_buffer) : vk::Buffer(buffer)),
		        .offset = 0,
		        .range = atlas_r8 ? input.atlas_table_bytes : VK_WHOLE_SIZE,
		};

		std::array descriptor_writes{
		        vk::WriteDescriptorSet{
		                .dstSet = pipeline.ds,
		                .dstBinding = 0,
		                .descriptorCount = input.sampler_a ? 2u : 1u,
		                .descriptorType = vk::DescriptorType::eCombinedImageSampler,
		                .pImageInfo = image_info.data(),
		        },
		        vk::WriteDescriptorSet{
		                .dstSet = pipeline.ds,
		                .dstBinding = 1,
		                .descriptorCount = 1,
		                .descriptorType = vk::DescriptorType::eCombinedImageSampler,
		                .pImageInfo = &motion_info,
		        },
		        vk::WriteDescriptorSet{
		                .dstSet = pipeline.ds,
		                .dstBinding = 2,
		                .descriptorCount = 1,
		                .descriptorType = vk::DescriptorType::eCombinedImageSampler,
		                .pImageInfo = &prev_info,
		        },
		        vk::WriteDescriptorSet{
		                .dstSet = pipeline.ds,
		                .dstBinding = 3,
		                .descriptorCount = 1,
		                .descriptorType = vk::DescriptorType::eCombinedImageSampler,
		                .pImageInfo = &atlas_r16_info,
		        },
		        vk::WriteDescriptorSet{
		                .dstSet = pipeline.ds,
		                .dstBinding = 4,
		                .descriptorCount = 1,
		                .descriptorType = atlas_r8 ? vk::DescriptorType::eCombinedImageSampler : vk::DescriptorType::eStorageImage,
		                .pImageInfo = &atlas_store_info,
		        },
		        vk::WriteDescriptorSet{
		                .dstSet = pipeline.ds,
		                .dstBinding = 5,
		                .descriptorCount = 1,
		                .descriptorType = atlas_r8 ? vk::DescriptorType::eStorageBuffer : vk::DescriptorType::eUniformBuffer,
		                .pBufferInfo = &atlas_table_info,
		        },
		        vk::WriteDescriptorSet{
		                .dstSet = pipeline.ds,
		                .dstBinding = 6,
		                .descriptorCount = 1,
		                .descriptorType = vk::DescriptorType::eCombinedImageSampler,
		                .pImageInfo = &atlas_rgba8_info,
		        },
		};

		vert_pc pc{
		        .rgb_rect = glm::ivec4(input.rect_rgb.offset.x,
		                               input.rect_rgb.offset.y,
		                               input.rect_rgb.extent.width,
		                               input.rect_rgb.extent.height),
		        .a_rect = glm::ivec4(input.rect_a.offset.x,
		                             input.rect_a.offset.y,
		                             input.rect_a.extent.width,
		                             input.rect_a.extent.height),
		        .scale = scale,
		        .bias = bias,
		        .post = {post.sharpness, post.vignette, post.vignette_inner, post.vignette_outer},
		        // motion.w and deband.w carry this eye's horizontal limits inside the
		        // decoded colour image, and glow.zw the edge bleed's ring width and its
		        // packed mode + fade distance. Packed rather than appended: see the
		        // static_assert on vert_pc.
		        .motion = {motion_step,
		                   motion_scale,
		                   blend_on ? blend.weight : 0.f,
		                   eye_x_limits(input.rect_rgb, foveation[view])[0]},
		        .glow = {post.glow,
		                 post.glow_margin,
		                 post.bleed_margin,
		                 // mode in the integer part, fade distance in the fraction. The
		                 // distance is clamped below 1 so it can never carry into the
		                 // mode, which would silently change what the ring does.
		                 post.bleed_extension + std::clamp(post.bleed_fade_distance, 0.f, 0.999f)},
		        // x debanding, y/z the low poly filter -- see the shader's `deband`.
		        .deband = {post.deband,
		                   post.low_poly,
		                   post.low_poly_levels,
		                   eye_x_limits(input.rect_rgb, foveation[view])[1]},
		};

		device.updateDescriptorSets(descriptor_writes, {});

		command_buffer.beginRenderPass(begin_info, vk::SubpassContents::eInline);
		command_buffer.bindPipeline(vk::PipelineBindPoint::eGraphics, *pipeline.pipeline);
		command_buffer.bindDescriptorSets(vk::PipelineBindPoint::eGraphics, *pipeline.layout, 0, pipeline.ds, {});
		command_buffer.pushConstants<vert_pc>(*pipeline.layout, vk::ShaderStageFlagBits::eVertex | vk::ShaderStageFlagBits::eFragment, 0, pc);
		if (atlas_r8 && atlas_vertex_warp)
		{
			command_buffer.bindVertexBuffers(0, vk::Buffer(atlas_mesh_buffers[view]), vk::DeviceSize{0});
			command_buffer.draw(atlas_mesh_counts[view], 1, 0, 0);
		}
		else
		{
			command_buffer.bindVertexBuffers(0, vk::Buffer(buffer), vertices_size * view);
			command_buffer.draw(uint32_t(drawn_vertices[view]), 1, 0, 0);
		}
		command_buffer.endRenderPass();
	}
}

static uint16_t count_pixels(const std::vector<uint16_t> & param)
{
	uint16_t res = 0;
	const int n_ratio = (param.size() - 1) / 2;
	for (auto [i, n_out]: utils::enumerate_range(param))
	{
		// number of output pixels per source pixels
		const int ratio = std::abs(n_ratio - int(i)) + 1;
		res += ratio * n_out;
	}
	return res;
}

XrExtent2Di stream_defoveator::defoveated_size(const wivrn::to_headset::foveation_parameter & view, float scale)
{
	// Scale changes viewport/swapchain size only. emit_full_view normalizes vertices
	// against the full foveation extent so lowering resolution preserves the FOV.
	//
	// Measured on a Pico 4: the pass renders 2160x2160 PER EYE, invariant across
	// stream_scale, because the defoveated size is what the panel wants and not what
	// the stream carries. At stream_scale 0.7 that is a 768x768 source blown up to
	// 2160x2160, 9.3 Mpixel a frame for 8.4 ms, 30-49% of the frame budget. The
	// runtime's compositor resamples this image anyway when it timewarps it, so
	// rendering fewer fragments and letting it do the last step is not a loss of a
	// resampling, it is the removal of a duplicated one.
	const auto apply = [scale](uint16_t v) -> int32_t {
		if (scale >= 1.0f)
			return v;
		// Even, and never zero: the foveation grid is laid out in whole pixels and a
		// zero-sized viewport is not a legal draw.
		const int32_t r = int32_t(std::lround(double(v) * double(scale)));
		return std::max<int32_t>(2, r & ~1);
	};
	return {
	        apply(count_pixels(view.x)),
	        apply(count_pixels(view.y)),
	};
}
